name: CI/CD ClienAppUa

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [master]
  pull_request:
    branches: [master]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
  # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
  #Steps
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install
        run: |
          npm install
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install ./google-chrome-stable_current_amd64.deb -y
      - name: CSS Linter
        run: npm run stylelint

      - name: Build
        run: |
          npm run build
          
      - name: env
        ## Another way reference your environment variables
        run: echo "The API key is:${{secrets.FIREBASE_API_KEY}}"
